# Host/port on which the proxy is running.
host: 0.0.0.0
port: 7777

# Maximum time of client inactivity in milliseconds
maxIdleTime: 30000

# Host/port of the server to be proxied
serverHost: 127.0.0.1
serverPort: 17777
